### ISSUE TITLE
Fork from dylanmckay/avr-llvm

### ISSUE THREAD

**Issue by RandomInsano** [sushihangover/llvm-avr#3]
At this point there is far more work done over there, so it might make sense to fork that or remove this Repository? It certainly threw me for a loop while looking for an llvm backend for AVR micro controllers.

Here's the full URL:

https://github.com/dylanmckay/avr-llvm

**Comment by dylanmckay** [comment]
I moved it into its own organisation here:

https://github.com/avr-llvm/llvm

**Comment by sushihangover** [comment]
I have a ton of changes along with a compliance test suite but have moved to other llvm embedded cpu work. Not sure if you are keeping up with the llvm master or how much other compliance work has been done but will update the readme on this repo to point people to your work on this (https://github.com/avr-llvm/llvm).

Thanks, R

**Comment by dylanmckay** [comment]
The repo I maintain is updated to LLVM master (approximately weekly), supports the entire instruction set, and has 95% of all machine code generation implemented and tested.
